
from enum import IntEnum


class StatusType(IntEnum):
  eBatteryVoltPercentage = 0
  eSpeedPercentageReport = 1
  eLowBattery = 2 
  eHighCurrent = 3 
  eComsLoss = 4
  eUnknownFault = 5
  eFaultCleared = 6
  
class MotorCmd(IntEnum):
  eModeCmd = 0
  eSpeedCmd = 1
  
class VescFaultCodes(IntEnum) :
  FAULT_CODE_NONE = 0
  FAULT_CODE_OVER_VOLTAGE = 1
  FAULT_CODE_UNDER_VOLTAGE = 2
  FAULT_CODE_DRV = 3
  FAULT_CODE_ABS_OVER_CURRENT = 4
  FAULT_CODE_OVER_TEMP_FET = 5
  FAULT_CODE_OVER_TEMP_MOTOR = 6
  FAULT_CODE_GATE_DRIVER_OVER_VOLTAGE = 7
  FAULT_CODE_GATE_DRIVER_UNDER_VOLTAGE = 8
  FAULT_CODE_MCU_UNDER_VOLTAGE = 9
  FAULT_CODE_BOOTING_FROM_WATCHDOG_RESET = 10
  FAULT_CODE_ENCODER_SPI = 11
  FAULT_CODE_ENCODER_SINCOS_BELOW_MIN_AMPLITUDE = 12
  FAULT_CODE_ENCODER_SINCOS_ABOVE_MAX_AMPLITUDE = 13
  FAULT_CODE_FLASH_CORRUPTION = 14
  FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_1 = 15
  FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_2 = 16
  FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_3 = 17
  FAULT_CODE_UNBALANCED_CURRENTS = 18
  FAULT_CODE_BRK = 19
  FAULT_CODE_RESOLVER_LOT = 20
  FAULT_CODE_RESOLVER_DOS = 21
  FAULT_CODE_RESOLVER_LOS = 22
  FAULT_CODE_FLASH_CORRUPTION_APP_CFG = 23
  FAULT_CODE_FLASH_CORRUPTION_MC_CFG = 24
  FAULT_CODE_ENCODER_NO_MAGNET = 25
  FAULT_CODE_ENCODER_MAGNET_TOO_STRONG = 26
  FAULT_CODE_PHASE_FILTER = 27
  FAULT_CODE_ENCODER_FAULT = 28
  FAULT_CODE_LV_OUTPUT_FAULT = 29