{
 "title": "Paddle IMU",
 "tags": [ "e-kayak" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "100ms",
 "templating": {
  "list": [
   {
    "name": "session",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"telemetry\", tag: \"session\", predicate: (r) => r._measurement == \"imu\", start: -30d)"
   }
  ]
 },
 "panels": [
  {
   "title": "Roll / Pitch / Yaw",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"imu\" and r.mode == \"manual\")\n  |> filter(fn: (r) => r._field == \"roll\" or r._field == \"pitch\" or r._field == \"yaw\")\n  |> filter(fn: (r) => if \"${session}\" == \"$__all\" then true else r.session == \"${session}\")"
    }
   ]
  },
  {
   "title": "Acceleration (X / Y / Z)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"imu\" and (r.mode == \"auto\" or r.mode == \"training\"))\n  |> filter(fn: (r) => r._field == \"accel_x\" or r._field == \"accel_y\" or r._field == \"accel_z\")\n  |> filter(fn: (r) => if \"${session}\" == \"$__all\" then true else r.session == \"${session}\")"
    }
   ]
  },
  {
   "title": "Gyroscope (X / Y / Z)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotationSpeed" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"imu\" and (r.mode == \"auto\" or r.mode == \"training\"))\n  |> filter(fn: (r) => r._field == \"gyro_x\" or r._field == \"gyro_y\" or r._field == \"gyro_z\")\n  |> filter(fn: (r) => if \"${session}\" == \"$__all\" then true else r.session == \"${session}\")"
    }
   ]
  }
 ]
}