---
rfManager:
  rfReadDataRateInMilliseconds: 50
  rfWriteDataRateInMilliseconds: 100
  rfLoggerVerbosityLevel: 1
  rfLoggerFilePath: /home/bradensunwold/Documents/e-kayak/pythonPi/logs/rfLog.txt
motorManager:
  maxCurrentInMilliAmps: 12000
