---
rfManager:
  rfReadDataRateInMilliseconds: 50
  rfWriteDataRateInMilliseconds: 100
  rfLoggerVerbosityLevel: 1
  rfLoggerFilePath: ~/Documents/python/ekayak/logs/rfLog.txt
motorManager:
  maxCurrentInMilliAmps: 12000
